# -*- coding: utf-8 -*-
"""Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IZTlVl_Gy4kF_X-YG8zCmtTAIDf8Bi0
"""

import pandas as pd
import string
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

nltk.download('stopwords')

df = pd.read_csv(r'/content/Tweets.csv')

df = df[['text', 'airline_sentiment']]

def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    text = text.lower()
    text = "".join([char for char in text if char not in string.punctuation])
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

df['Processed_Text'] = df['text'].apply(preprocess_text)

X_train, X_test, y_train, y_test = train_test_split(df['Processed_Text'], df['airline_sentiment'], test_size=0.2, random_state=42)

vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

y_pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")
print("Classification Report:\n", classification_report(y_test, y_pred))

new_tweet = ["I love flying with this airline, amazing service!"]
new_tweet_processed = vectorizer.transform([preprocess_text(new_tweet[0])])
predicted_sentiment = model.predict(new_tweet_processed)
print(f"Predicted Sentiment: {predicted_sentiment[0]}")